/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusChip: typeof import('./components/StatusChip.vue')['default']
    StatusList: typeof import('./components/StatusList.vue')['default']
    TaskDetails: typeof import('./components/TaskDetails.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TaskParent: typeof import('./components/TaskParent.vue')['default']
    UserChip: typeof import('./components/UserChip.vue')['default']
    UserList: typeof import('./components/UserList.vue')['default']
  }
}
